### PR TITLE
Add factory_boy and define initial factories

### PR DESCRIPTION
**Pull request by werberger**
This resolves issue #104 (add development fixtures). Although a factory has not been defined for _Activity_

### CODE REVIEW

**Review by brylie — CHANGES_REQUESTED** [review]
Let's add the `.idea` folder to `.gitignore` so we don't commit IDE metadata to the repository.

**Review by brylie — COMMENTED** [review]
Overall, this looks great :-)

**Comment by werberger** [comment]
I think I've done it. Let me know if I should have done anything differently.

**Review by brylie — APPROVED** [review]

**Review by brylie — CHANGES_REQUESTED** [review]
Be sure to check the code for lint, such as by running `isort` and `black` on the files. Here, `isort` is raising the following errors.

> ERROR: /home/runner/work/companionship-care/companionship-care/project/accounts/factories.py Imports are incorrectly sorted and/or formatted.
ERROR: /home/runner/work/companionship-care/companionship-care/project/circles/views.py Imports are incorrectly sorted and/or formatted.
ERROR: /home/runner/work/companionship-care/companionship-care/project/circles/factories.py Imports are incorrectly sorted and/or formatted.
ERROR: /home/runner/work/companionship-care/companionship-care/project/caregivers/factories.py Imports are incorrectly sorted and/or formatted.
ERROR: /home/runner/work/companionship-care/companionship-care/project/error_handling/views.py Imports are incorrectly sorted and/or formatted.

**Comment by werberger** [comment]
I ran _isort_ and _black_ which fixed up a number of things. _Flake8_ threw many errors (>150k), so assumed they are already known about. test coverage is 83%.

I hope that's everything. But if not, I guess it's all learning for future PRs.

**Pull request merged**
