### PR TITLE
Install Pre-commit with configuration

### LINKED ISSUE #92: Configure pre-commit and Pre-Commit CI for project
The `pre-commit` script can help enforce good code practices. Similarly, Pre-Commit CI can auto-check pre-commit rules on pull requests.

## Task

- [ ] configure `pre-commit` for this project
- [ ] optionally, consider enabling Pre-Commit CI on this repo

## Resources

- https://github.com/asottile/pyupgrade
- https://pre-commit.ci/
- https://pycqa.github.io/isort/docs/configuration/pre-commit.html
- https://github.com/asottile/pyupgrade

### PR DESCRIPTION
**Pull request by Devdarji**
Closes #92

### CODE REVIEW

**Comment by brylie** [comment]
Please make sure y
When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

**Comment by brylie** [comment]
@Devdarji, thank you for opening this pull request. Please add a comment in the related issue to claim it so other developers can see which tasks are available.

**Review by brylie — CHANGES_REQUESTED** [review]
@Devdarji, thank you for opening this pull request. Please add a comment in the related issue to claim it so other developers can see which tasks are available.

**Review by brylie — CHANGES_REQUESTED** [review]
When creating a pull request that will resolve an issue, please [link the pull request to the related issue(s)](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) by using one of the [supported keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) followed by the issue number.

For example:

```
Closes #<issue-number>
```

## Further details

> You can link a pull request to an issue by using a supported keyword in the pull request's description or in a commit message.
> 
> - close
> - closes
> - closed
> - fix
> - fixes
> - fixed
> - resolve
> - resolves
> - resolved

**Review by brylie — CHANGES_REQUESTED** [review]
Please remove changes from this pull request unrelated to the `.pre-commit-config.yaml`.

**Comment by Devdarji** [comment]
Closes #92

**Comment by Devdarji** [comment]
Closes #92

**Review by brylie — CHANGES_REQUESTED** [review]
@Devdarji, perhaps start this PR from a new branch and include only the `.pre-commit-config.yaml`? All of the other files are unrelated to the task.

**Comment by brylie** [comment]
Please close this pull request and start a new one with the single file. In the pull request description, write “Closes #92”

**Comment by Devdarji** [comment]
ok

**Pull request closed without merging**
