### PR TITLE
Register admin for remaining models

### LINKED ISSUE #129: Register all models with Django Admin
We haven't registered all project models with the Django Admin, making it difficult to manage content in a centralized manner.

## Task

For each model in our project,
- [ ] register the model with the Django Admin, if not already registered

## Resources

- https://docs.djangoproject.com/en/4.1/ref/contrib/admin/#modeladmin-objects

### PR DESCRIPTION
**Pull request by kishan3**
Closes #129

### CODE REVIEW

**Comment by kishan3** [comment]
@brylie Please let me know if I missed any models.

**Comment by brylie** [comment]
@kishan3, thank you for opening this pull request. Please add a comment in the related issue to claim it so other developers can see which tasks are available.

**Comment by kishan3** [comment]
Fixed in https://github.com/CompanionshipCare/companionship-care/pull/130

**Comment by brylie** [comment]
@kishan3, please add a comment in issue #129 so that you can claim that issue.

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
@all-contributors please add @kishan3 for code

**Pull request merged**
